using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace WPR.Mvvm.SourceGen;

[Generator]
public class ObservableModelGenerator : BaseGeneric1Generator
{
    // Ищем наследников базового типа с одним типовым аргументом: ObservableModel<T>
    protected override string TargetBaseTypeName => "ObservableModel";

    // Сохраняем прежнее имя генерируемого файла
    protected override string HintSuffix => "ObservableModelFromModel";

    // Префикс для Diagnostic.Id
    protected override string DiagnosticIdPrefix => "WPRSG";

    // Метадатное имя атрибута исключения свойств
    private const string SkipPropertyAttributeMetadataName = "WPR.Mvvm.Attributes.SkipPropertyAttribute";

    // Основная генерация для конкретного класса + типа модели
    protected override string GenerateFor(INamedTypeSymbol classSymbol, ITypeSymbol modelTypeSymbol, Compilation compilation)
    {
        // Генерируем ТОЛЬКО для ПРЯМЫХ наследников ObservableModel<T>, чтобы не дублировать свойства в потомках
        if (classSymbol.BaseType is not INamedTypeSymbol { IsGenericType: true, TypeArguments.Length: 1 } directBase
            || directBase.Name != TargetBaseTypeName)
        {
            return string.Empty;
        }

        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();

        const string modelFieldName = "Model";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Сгенерировано ObservableModelGenerator");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.ObjectModel;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        var classDeclaration = GeneratePartialClassDeclaration(classSymbol);
        sb.AppendLine(classDeclaration);
        sb.AppendLine("{");

        if (modelTypeSymbol is not INamedTypeSymbol modelNamed)
        {
            sb.AppendLine("    // Не удалось разрешить тип модели T во время генерации. Генерация пропущена.");
            sb.AppendLine("}"); // end class

            if (!string.IsNullOrEmpty(ns))
                sb.AppendLine("}"); // end namespace

            return sb.ToString();
        }

        // Собираем список исключаемых свойств из атрибутов класса VM
        var skippedPropertyNames = GetSkippedPropertyNames(classSymbol);

        var modelProperties = GetAllModelProperties(modelNamed);
        var existingMemberNames = new HashSet<string>(classSymbol.GetMembers().Select(m => m.Name));

        foreach (var prop in modelProperties)
        {
            if (prop.IsIndexer) continue;

            var propName = prop.Name;

            // Пропускаем свойство, если оно явно исключено атрибутом
            if (skippedPropertyNames.Contains(propName))
            {
                sb.AppendLine($"    // Пропущено: свойство '{propName}' отмечено атрибутом SkipPropertyAttribute.");
                sb.AppendLine();
                continue;
            }

            if (existingMemberNames.Contains(propName))
            {
                sb.AppendLine($"    // Пропущено: свойство '{propName}' уже определено в {classSymbol.Name}.");
                sb.AppendLine();
                continue;
            }

            var targetTypeSymbol = GetTargetGeneratedType(prop.Type, compilation);
            var targetTypeName = targetTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Свойство для модели {modelNamed.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}.{propName}");
            sb.AppendLine("    /// </summary>");

            string setterFieldName;
            var isCollection = IsObservableCollectionTypeSymbol(targetTypeSymbol);
            var isPublicSetter = prop.SetMethod is { DeclaredAccessibility: Accessibility.Public, IsInitOnly: false };
            
            // Геттер
            if (isCollection)
            {
                setterFieldName = "_" + ToCamelCase(propName);
                sb.AppendLine($"    private {targetTypeName} {setterFieldName};");
            }
            else
            {
                setterFieldName = $"{modelFieldName}.{propName}";
            }

            sb.AppendLine($"    public {targetTypeName} {propName}");
            sb.AppendLine("    {");

            if (isCollection)
                sb.AppendLine($"        get => {setterFieldName} ??= {modelFieldName}.{propName} is null ? null : new {targetTypeName}({modelFieldName}.{propName});");
            else
                sb.AppendLine($"        get => {setterFieldName};");
            
            // Публичный сеттер
            if (isPublicSetter)
            {
                if (isCollection)
                {
                    sb.AppendLine("        set");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            if (SetProperty(ref {setterFieldName}, value) && value == null)");
                    sb.AppendLine($"                {modelFieldName}.{propName} = null;");
                    sb.AppendLine($"                On{propName}Changed(value);");
                    sb.AppendLine("        }");
                }
                else
                {
                    sb.AppendLine("        set");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            if (SetProperty({setterFieldName}, value, {modelFieldName}, (m, v) => m.{propName} = v))");
                    sb.AppendLine($"                On{propName}Changed(value);");
                    sb.AppendLine("        }");
                }
            }

            sb.AppendLine("    }");

            if (isPublicSetter)
            {
                // OnPropertyChanged Метод
                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// Вызывается после изменения свойства {propName}");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    partial void On{propName}Changed({targetTypeName} value);");
            }
            
            sb.AppendLine();
            sb.AppendLine();
        }

        var hasSingleModelCtor = classSymbol.InstanceConstructors.Any(ctor =>
            !ctor.IsStatic &&
            ctor.Parameters.Length == 1 &&
            SymbolEqualityComparer.Default.Equals(ctor.Parameters[0].Type, modelTypeSymbol));

        if (hasSingleModelCtor)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Оператор неявного преобразования модели {modelNamed.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}");
            sb.AppendLine("    /// Сгенерировано ObservableModelGenerator.");
            sb.AppendLine("    /// </summary>");

            sb.AppendLine($"    public static implicit operator {classSymbol.Name}({modelTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} model)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (model is null) return null;");
            sb.AppendLine($"        var vm = new {classSymbol.Name}(model);");
            sb.AppendLine("        return vm;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    // Пропущено: оператор неявного преобразования не сгенерирован, так как отсутствует конструктор {classSymbol.Name}({modelNamed.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} model).");
        }

        sb.AppendLine("}"); // end class

        if (!string.IsNullOrEmpty(ns))
            sb.AppendLine("}"); // end namespace

        return sb.ToString();
    }

    // Собираем имена исключаемых свойств из SkipPropertyAttribute на классе VM
    private static HashSet<string> GetSkippedPropertyNames(INamedTypeSymbol classSymbol)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);

        foreach (var attr in classSymbol.GetAttributes())
        {
            var attrClass = attr.AttributeClass;
            if (attrClass == null) continue;

            var isSkipAttr =
                string.Equals(attrClass.ToDisplayString(), SkipPropertyAttributeMetadataName, StringComparison.Ordinal)
                || string.Equals(attrClass.Name, "SkipPropertyAttribute", StringComparison.Ordinal);

            if (!isSkipAttr) continue;

            // Конструктор: params string[] propertyNames
            if (attr.ConstructorArguments.Length == 1)
            {
                var arg = attr.ConstructorArguments[0];

                if (arg.Kind == TypedConstantKind.Array)
                {
                    foreach (var v in arg.Values)
                        if (v.Value is string s && !string.IsNullOrWhiteSpace(s))
                            result.Add(s);
                }
                else if (arg.Value is string s && !string.IsNullOrWhiteSpace(s))
                {
                    result.Add(s);
                }
            }

            // На всякий случай поддержим именованные аргументы: PropertyName / PropertyNames
            foreach (var na in attr.NamedArguments)
            {
                if (na.Key is "PropertyName" or "PropertyNames")
                {
                    var val = na.Value;
                    if (val.Kind == TypedConstantKind.Array)
                    {
                        foreach (var v in val.Values)
                            if (v.Value is string s && !string.IsNullOrWhiteSpace(s))
                                result.Add(s);
                    }
                    else if (val.Value is string s && !string.IsNullOrWhiteSpace(s))
                    {
                        result.Add(s);
                    }
                }
            }
        }

        return result;
    }
}