<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <IsRoslynComponent>true</IsRoslynComponent>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>Генератор ViewModels для WPR.Mvvm</Title>
        <PackageIcon>nuget-icon-128.png</PackageIcon>
        <Version>1.0.1</Version>
    </PropertyGroup>

    <ItemGroup>
        <!-- Roslyn API для компиляции генератора.
             PrivateAssets="all" не позволит транзитивно тянуть эти пакеты в проекты-приложения -->
        <PackageReference Include="Microsoft.CodeAnalysis" Version="4.11.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" PrivateAssets="all" />
        <!-- (опционально, но полезно) Доп. правила для самих анализаторов -->
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <!-- Указываем, что этот проект — анализатор -->
        <None Include="$(OutputPath)\WPR.Mvvm.SourceGen.dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
        <None Update="nuget-icon-128.png">
          <Pack>True</Pack>
          <PackagePath></PackagePath>
        </None>
    </ItemGroup>

</Project>