<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWpf>true</UseWpf>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    </ItemGroup>

<!--    <ItemGroup>-->
<!--        <PackageReference Include="WPR.Mvvm.SourceGen" Version="1.0.1">-->
<!--            &lt;!&ndash; Эти ассеты используются текущей библиотекой &ndash;&gt;-->
<!--            <IncludeAssets>analyzers; build; buildTransitive</IncludeAssets>-->
<!--            &lt;!&ndash; Эти ассеты не «уходят» транзитивно; analyzers намеренно НЕ включаем,-->
<!--                 чтобы они как раз доходили до потребителя &ndash;&gt;-->
<!--            <PrivateAssets>compile; runtime; native; contentfiles; buildMultitargeting</PrivateAssets>-->
<!--        </PackageReference>-->
<!--    </ItemGroup>-->

</Project>
