<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8;net9</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Репозитории сущностей EF Core</Title>
    <Description>Репозитории сущностей EF Core</Description>
    <PackageIcon>nuget-icon-128.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\nuget-icon-128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WPR.Repository.Abstractions\WPR.Repository.Abstractions.csproj" />
  </ItemGroup>

</Project>
