<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Mapped Репозитории сущностей EF Core</Title>
    <Description>Mapped Репозитории сущностей EF Core.
Для автоматического или ручного маппинга сущности БД в DTO и обратно
Используется библиотека Mapster внутри</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>nuget-icon-128.png</PackageIcon>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\nuget-icon-128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="WPR.Repository.EfCore" Version="1.0.3" />
  </ItemGroup>

</Project>
