<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>Интерфейсы Generic репозиториев</Title>
		<Description>Интерфейсы Generic репозиториев</Description>
		<PackageIcon>nuget-icon-128.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Version>1.0.3</Version>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\nuget-icon-128.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
