<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>1.0</Version>
		<PackageReleaseNotes>
			Стили базовых элементов и некоторые дополнительные контролы
		</PackageReleaseNotes>
	</PropertyGroup>

	<PropertyGroup>
		<LangVersion>Latest</LangVersion>
		<TargetFrameworks>net8.0-windows;net9.0-windows</TargetFrameworks>
		<UseWPF>true</UseWPF>
		<PublishReadyToRun>True</PublishReadyToRun>
		<PackageId>WPR.Styles</PackageId>
		<Authors>tj_d</Authors>
		<Product>tj_d</Product>
		<Description>Пакет стилей и дополнительных контролов WPF под .Net Core в стиле Material Design</Description>
		<Copyright>tj.den88@gmail.com</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/tjden88/WPR.Styles</PackageProjectUrl>
		<RepositoryUrl>https://github.com/tjden88/WPR.Styles</RepositoryUrl>
		<PackageTags>WPF;Styles;Templates</PackageTags>
		<SignAssembly>false</SignAssembly>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Fonts\Montserrat-Italic-VariableFont_wght.ttf" />
		<None Remove="Fonts\Montserrat-VariableFont_wght.ttf" />
		<None Remove="Fonts\Roboto-Black.ttf" />
		<None Remove="Fonts\Roboto-BlackItalic.ttf" />
		<None Remove="Fonts\Roboto-BoldItalic.ttf" />
		<None Remove="Fonts\RobotoCondensed-Bold.ttf" />
		<None Remove="Fonts\RobotoCondensed-BoldItalic.ttf" />
		<None Remove="Fonts\RobotoCondensed-Italic.ttf" />
		<None Remove="Fonts\RobotoCondensed-Light.ttf" />
		<None Remove="Fonts\RobotoCondensed-LightItalic.ttf" />
		<None Remove="Fonts\RobotoCondensed-Regular.ttf" />
		<None Remove="Usage.txt" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="Usage.txt" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Fonts\Montserrat-Italic-VariableFont_wght.ttf" />
		<Resource Include="Fonts\Montserrat-VariableFont_wght.ttf" />
	</ItemGroup>

</Project>
